# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 4.3"
gem "jekyll-last-modified-at", git: "https://github.com/maximevaillancourt/jekyll-last-modified-at", branch: "add-support-for-files-in-git-submodules"
#gem "webrick", "~> 1.8"
gem "webrick", "1.8.2"
# gem "nokogiri"
#gem "nokogiri", "1.16.2"
#gem "nokogiri", "1.16.5"
gem "nokogiri", ">= 1.18.3"